/**
 * packages/system-api/src/config/labels.ts
 *
 * Error codes and status labels for Frontend consumption
 */

export const API_LABELS = {
    ERRORS: {
        NOT_FOUND: 'API.ERRORS.NOT_FOUND',
        ALREADY_EXISTS: 'API.ERRORS.ALREADY_EXISTS',
        INVALID_PATH: 'API.ERRORS.INVALID_PATH',
        INVALID_NAME: 'API.ERRORS.INVALID_NAME',
        INVALID_DATASOURCE: 'API.ERRORS.INVALID_DATASOURCE',
        HAS_CHILDREN: 'API.ERRORS.HAS_CHILDREN',
        CATEGORY_HAS_CHILDREN: 'API.ERRORS.CATEGORY_HAS_CHILDREN',
        INVALID_DOMAIN: 'API.ERRORS.INVALID_DOMAIN',
        SERVER_ERROR: 'API.ERRORS.SERVER_ERROR'
    },
    SUCCESS: {
        KEY_CREATED: 'API.SUCCESS.KEY_CREATED',
        KEY_DELETED: 'API.SUCCESS.KEY_DELETED',
        KEY_UPDATED: 'API.SUCCESS.KEY_UPDATED',
        CORS_CREATED: 'API.SUCCESS.CORS_CREATED',
        CORS_DELETED: 'API.SUCCESS.CORS_DELETED',
        CORS_UPDATED: 'API.SUCCESS.CORS_UPDATED',
        CATEGORY_SAVED: 'API.SUCCESS.CATEGORY_SAVED',
        CATEGORY_DELETED: 'API.SUCCESS.CATEGORY_DELETED',
        ENDPOINT_SAVED: 'API.SUCCESS.ENDPOINT_SAVED',
        ENDPOINT_DELETED: 'API.SUCCESS.ENDPOINT_DELETED',
        ENDPOINT_UPDATED: 'API.SUCCESS.ENDPOINT_UPDATED'
    }
} as const;
