/**
 * packages/system-datasource/src/config/labels.ts
 *
 * Centralized Labels & Messages for System Datasource
 * STRICTLY FORBIDDEN to hardcode strings in logic files.
 *
 * UPDATED: Uses Translation Keys (i18n friendly) instead of hardcoded English.
 */

export const LABELS = {
    SUCCESS: {
        SOURCE_CREATED: 'DS.SUCCESS.SOURCE_CREATED',
        SOURCE_DELETED: 'DS.SUCCESS.SOURCE_DELETED',
        SOURCE_CLONED: 'DS.SUCCESS.SOURCE_CLONED',
        SOURCE_UPDATED: 'DS.SUCCESS.SOURCE_UPDATED',
        SOURCE_ARCHIVED: 'DS.SUCCESS.SOURCE_ARCHIVED',
        SOURCE_RESTORED: 'DS.SUCCESS.SOURCE_RESTORED',
        SCHEMA_UPDATED: 'DS.SUCCESS.SCHEMA_UPDATED',
        COLUMN_ADDED: 'DS.SUCCESS.COLUMN_ADDED',
        COLUMN_DROPPED: 'DS.SUCCESS.COLUMN_DROPPED',
        RESOURCE_CREATED: 'DS.SUCCESS.RESOURCE_CREATED',
        RESOURCE_UPDATED: 'DS.SUCCESS.RESOURCE_UPDATED',
        RESOURCE_DELETED: 'DS.SUCCESS.RESOURCE_DELETED',
        DATA_IMPORTED: 'DS.SUCCESS.DATA_IMPORTED',
        ROW_INSERTED: 'DS.SUCCESS.ROW_INSERTED',
        ROW_UPDATED: 'DS.SUCCESS.ROW_UPDATED',
        ROW_DELETED: 'DS.SUCCESS.ROW_DELETED',
        ROWS_DELETED: 'DS.SUCCESS.ROWS_DELETED', // Was dynamic, now static key
        RELATION_ADDED: 'DS.SUCCESS.RELATION_ADDED',
        RELATION_UPDATED: 'DS.SUCCESS.RELATION_UPDATED',
        RELATION_DELETED: 'DS.SUCCESS.RELATION_DELETED',
    },
    ERROR: {
        SCHEMA_FAILED: 'DS.ERROR.SCHEMA_FAILED',
        LOAD_FAILED: 'DS.ERROR.LOAD_FAILED',
        CLONE_FAILED: 'DS.ERROR.CLONE_FAILED',
        ARCHIVE_FAILED: 'DS.ERROR.ARCHIVE_FAILED',
        RESTORE_FAILED: 'DS.ERROR.RESTORE_FAILED',
        RESOURCE_LOAD_FAILED: 'DS.ERROR.RESOURCE_LOAD_FAILED',
        RESOURCE_CREATE_FAILED: 'DS.ERROR.RESOURCE_CREATE_FAILED',
        RESOURCE_UPDATE_FAILED: 'DS.ERROR.RESOURCE_UPDATE_FAILED',
        RESOURCE_DELETE_FAILED: 'DS.ERROR.RESOURCE_DELETE_FAILED',
        DATA_LOAD_FAILED: 'DS.ERROR.DATA_LOAD_FAILED',
        ROW_INSERT_FAILED: 'DS.ERROR.ROW_INSERT_FAILED',
        ROW_UPDATE_FAILED: 'DS.ERROR.ROW_UPDATE_FAILED',
        ROW_DELETE_FAILED: 'DS.ERROR.ROW_DELETE_FAILED',
        RELATION_FAILED: 'DS.ERROR.RELATION_FAILED',
        NOT_FOUND: 'DS.ERROR.NOT_FOUND',
        ALREADY_EXISTS: 'DS.ERROR.ALREADY_EXISTS',
        CONFLICT: 'DS.ERROR.CONFLICT',
        AUTHENTICATION_REQUIRED: 'DS.ERROR.AUTHENTICATION_REQUIRED',
        SCHEMA_NOT_FOUND: 'DS.ERROR.SCHEMA_NOT_FOUND',
        NO_WRITABLE_FIELDS: 'DS.ERROR.NO_WRITABLE_FIELDS',
        OWNERSHIP_DENIED: 'DS.ERROR.OWNERSHIP_DENIED',
        INVALID_RELATION_TYPE: 'DS.ERROR.INVALID_RELATION_TYPE',
        SELF_RELATION_NOT_ALLOWED: 'DS.ERROR.SELF_RELATION_NOT_ALLOWED',
        RELATION_EXISTS: 'DS.ERROR.RELATION_EXISTS',
        TARGET_NOT_FOUND: 'DS.ERROR.TARGET_NOT_FOUND',
        SOURCE_NOT_FOUND: 'DS.ERROR.SOURCE_NOT_FOUND',
        INVALID_IDS: 'DS.ERROR.INVALID_IDS',
        ARRAY_OF_ROWS_REQUIRED: 'DS.ERROR.ARRAY_OF_ROWS_REQUIRED',
        NO_VALID_COLUMNS: 'DS.ERROR.NO_VALID_COLUMNS',
        CANNOT_RELATE_TO_SYSTEM_USERS: 'DS.ERROR.CANNOT_RELATE_TO_SYSTEM_USERS',
        NOT_A_RELATION: 'DS.ERROR.NOT_A_RELATION',
        CANNOT_RENAME_COLUMN: 'DS.ERROR.CANNOT_RENAME_COLUMN',
        CANNOT_DROP_ID: 'DS.ERROR.CANNOT_DROP_ID',
        COLUMN_NOT_FOUND: 'DS.ERROR.COLUMN_NOT_FOUND',
        MUTATION_LOG_FAILED: 'DS.ERROR.MUTATION_LOG_FAILED',
        FK_CREATION_WARNING: 'DS.ERROR.FK_CREATION_WARNING',
        RESOLVER_PARSE_ERROR: 'DS.ERROR.RESOLVER_PARSE_ERROR',
    },
    CONFIRM: {
        DELETE_SOURCE: 'DS.CONFIRM.DELETE_SOURCE',
        DROP_COLUMN: 'DS.CONFIRM.DROP_COLUMN',
        DELETE_ROW: 'DS.CONFIRM.DELETE_ROW',
    },
    VALIDATION: {
        COLUMN_NAME_REQUIRED: 'DS.VALIDATION.COLUMN_NAME_REQUIRED',
        COLUMN_TYPE_REQUIRED: 'DS.VALIDATION.COLUMN_TYPE_REQUIRED',
        COLUMN_VALUES_REQUIRED: 'DS.VALIDATION.COLUMN_VALUES_REQUIRED', // Was dynamic
        COLUMN_TARGET_REQUIRED: 'DS.VALIDATION.COLUMN_TARGET_REQUIRED', // Was dynamic
        DUPLICATE_COLUMN_NAMES: 'DS.VALIDATION.DUPLICATE_COLUMN_NAMES', // Was dynamic
        RESOURCE_NAME_REQUIRED: 'DS.VALIDATION.RESOURCE_NAME_REQUIRED',
        SLUG_REQUIRED: 'DS.VALIDATION.SLUG_REQUIRED',
        FIELDS_REQUIRED: 'DS.VALIDATION.FIELDS_REQUIRED',
        SELECT_TARGET_TABLE: 'DS.VALIDATION.SELECT_TARGET_TABLE',
        TABLE_NAME_REQUIRED: 'DS.VALIDATION.TABLE_NAME_REQUIRED',
        MIN_ONE_COLUMN: 'DS.VALIDATION.MIN_ONE_COLUMN',
        INVALID_SCHEMA: 'DS.VALIDATION.INVALID_SCHEMA',
        INVALID_ROW_ID: 'DS.VALIDATION.INVALID_ROW_ID',
        INVALID_TABLE_NAME: 'DS.VALIDATION.INVALID_TABLE_NAME',
        INVALID_COLUMN_NAME: 'DS.VALIDATION.INVALID_COLUMN_NAME', // Was dynamic
        MAX_BULK_ITEMS: 'DS.VALIDATION.MAX_BULK_ITEMS', // Was dynamic
    },
} as const;

export const BACKEND_MESSAGES = {
    ERROR_CREATING_TABLE: 'DS.BACKEND.ERROR_CREATING_TABLE',
    ERROR_DROPPING_TABLE: 'DS.BACKEND.ERROR_DROPPING_TABLE',
    ERROR_ALTERING_TABLE: 'DS.BACKEND.ERROR_ALTERING_TABLE',
    ERROR_EXECUTING_QUERY: 'DS.BACKEND.ERROR_EXECUTING_QUERY',
    TABLE_NOT_FOUND: 'DS.BACKEND.TABLE_NOT_FOUND',
    COLUMN_NOT_FOUND: 'DS.BACKEND.COLUMN_NOT_FOUND',
    INVALID_COLUMN_TYPE: 'DS.BACKEND.INVALID_COLUMN_TYPE',
    RELATION_ERROR: 'DS.BACKEND.RELATION_ERROR',
} as const;
