export const DYNAMIC_ROUTES_LABELS = {
    routeBuilder: {
        title: 'Route Builder',
        subtitle: 'Manage dynamic API routes and data binding',
        labels: {
            loading: 'Loading API Management...',
            categories: 'Categories',
            endpoints: 'Endpoints',
            endpoint: 'endpoint',
            noCategories: 'No categories yet',
            noEndpoints: 'No endpoints in this category',
            allCategories: 'All Cat.',
            method: 'Method',
            name: 'Name',
            description: 'Description',
            path: 'Path',
            roles: 'Roles',
            permissions: 'Permissions',
            minLevel: 'Min Level',
            levelShort: 'Lv.',
            dataSource: 'Data Source',
            resource: 'Resource',
            responseType: 'Response Type',
            staticJson: 'Static JSON',
            active: 'Active',
            inactive: 'Inactive',
            publicRoutes: 'Public Routes',
            authRequired: 'Auth Required',
            responseData: 'Response Data',
            noneSelected: 'None selected',
            selectCategory: 'Select category',
            selectDataSource: 'Select Data Source',
            selectResource: 'Select Resource',
            noDataSources: 'No data sources',
            noResources: 'No resources',
            rateLimit: 'Rate Limit',
            apiKey: 'API Key',
            lastUsed: 'Last Used',
            tableData: 'Table Data (Default)',
        },
        buttons: {
            createEndpoint: 'Create Endpoint',
            generateKey: 'Generate API Key',
            testEndpoint: 'Test Endpoint',
            new: 'New',
            newEndpoint: 'New Endpoint',
            newCategory: 'New Category',
            edit: 'Edit',
            delete: 'Delete',
            cancel: 'Cancel',
            save: 'Save',
            saveCategory: 'Save Category',
            saveEndpoint: 'Save Endpoint',
            test: 'Test',
            copy: 'Copy',
            clone: 'Clone',
            auth: 'Auth',
            routes: 'Routes',
            apiTester: 'API Tester',
            back: 'Back',
        },
        columns: {
            endpoint: 'Endpoint',
            method: 'Method',
            rateLimit: 'Rate Limit',
            apiKey: 'API Key',
            lastUsed: 'Last Used',
        },
        placeholders: {
            categoryName: 'Category name',
            categoryDescription: 'Category description (optional)',
            endpointPath: '/path/to/endpoint',
            endpointDescription: 'Endpoint description',
            jsonData: 'JSON Response Data',
            rolesCommaSep: 'Roles (comma separated)',
            permissionsCommaSep: 'Permissions (comma separated)',
            searchEndpoints: 'Search endpoints...',
        },
        messages: {
            categorySaved: 'Category saved',
            categoryDeleted: 'Category deleted',
            endpointSaved: 'Endpoint saved',
            endpointDeleted: 'Endpoint deleted',
            endpointToggled: 'Endpoint status updated',
            copiedPath: 'Path copied!',
            confirmDeleteCategory: 'Delete this category?',
            confirmDeleteEndpoint: 'Delete this endpoint?',
            fetchError: 'Failed to fetch data',
            saveError: 'Failed to save',
            deleteError: 'Failed to delete',
            swaggerExported: 'Swagger JSON exported!',
            schemaCopied: 'Schema copied',
            noDescription: 'No description',
            noDescriptionProvided: 'No description provided for this endpoint.',
        },
        explorer: {
            developerPortal: 'Developer Portal',
            title: 'API Explorer',
            subtitle: 'Discover, test, and integrate APIs directly into your application.',
            downloadOpenApi: 'Download OpenAPI',
            requiredRoleLevel: 'Required Role Level:',
            category: 'Category:',
            uncategorized: 'Uncategorized',
            responseSchema: 'Response Schema',
            viewDetails: 'View Details',
            tryItOut: 'Try it out',
            noEndpointSelected: 'No Endpoint Selected',
            selectEndpointHint: 'Select an endpoint from the sidebar to view details',
        },
        tabs: {
            basic: 'Basic Info',
            data: 'Data Binding',
            mutation: 'Mutation',
            security: 'Security',
            response: 'Response',
            test: 'Quick Test',
        },
        detail: {
            fullUrl: 'Full URL',
            requestInfo: 'Request Info',
            method: 'Method',
            contentType: 'Content-Type',
            security: 'Security',
            codeExamples: 'Code Examples',
            responseTemplate: 'Response Template',
            dataSource: 'Data Source',
            status: 'Status',
            publicAccess: 'Public Access',
            minRoleLevel: 'Min Role Level',
            noDataSource: 'No data source',
            active: 'Active',
            inactive: 'Inactive',
            backToList: '← Back to List',
            edit: 'Edit',
            test: 'Test',
            endpointNotFound: 'Endpoint not found',
            errorResponses: 'Error Responses',
            errorResponsesHint: 'Use errorCode for i18n translations in your frontend',
            successResponse: 'Success Response',
            possibleErrors: 'Possible Errors',
            errorCode: 'Error Code',
            httpStatus: 'HTTP Status',
            defaultMessage: 'Default Message',
            autoGenerated: 'Auto-generated',
            customOverride: 'Custom Override',
        },
        mutation: {
            title: 'Write Operation Configuration',
            operationBehavior: 'Operation Behavior',
            ownershipSecurity: 'Ownership & Security',
            restrictToOwner: 'Restrict to Owner',
            restrictToOwnerHint: 'Only allow users to modify their own records',
            ownershipColumn: 'Ownership Column',
            ownershipColumnHint: 'Column in the table that stores the Owner ID',
            fieldControl: 'Field Control',
            writableFields: 'Writable Fields (JSON Array)',
            writableFieldsHint: 'Leave empty to allow all (except protected)',
            protectedFields: 'Protected Fields (JSON Array)',
            autoPopulate: 'Auto-Populate (JSON Object)',
            columnSelector: 'Column Configuration',
            columnSelectorHint: 'Click columns to toggle their write permission',
            selectDataSourceFirst: 'Select a Data Source first to see available columns',
            noColumnsAvailable: 'No columns available for this data source',
            legendWritable: 'Writable',
            legendProtected: 'Protected',
            legendAutoPopulate: 'Auto-Populate',
            validationRules: 'Validation Rules',
            validationHint: 'Enter validation rules for each writable column',
            validationSyntax: 'Syntax: required, minLength:N, maxLength:N, format:email|url, enum:val1,val2',
            autoPopulateHint: 'Select fields to auto-fill with system values',
            autoPopNone: '— No auto-fill —',
            autoPopUserId: 'User ID ({{USER_ID}})',
            autoPopUserIdRecommended: 'Recommended: User ID ({{USER_ID}})',
            autoPopNow: 'Current Time ({{NOW}})',
            autoPopUserRole: 'User Role ({{USER_ROLE}})',
            relationArrow: '→ ',
        },
        misc: {
            dangerZone: 'Danger Zone',
            openInTester: 'Open in API Tester',
            clickToTest: 'Click the button below to test this endpoint in the API Tester',
            noEndpointsOne: 'No endpoints defined yet',
            noEndpointsTwo: 'Click "New Endpoint" to create your first API route',
            noEndpointsFilter: 'No endpoints match your filters',
            tryAdjusting: 'Try adjusting your search or filter criteria',
            noneSelected: 'None selected',
            selectToAdd: 'Select to add...',
            dataPreview: 'Data Preview',
            dataPreviewHint: 'Data from this source will be injected into {{DATA}} variable in your response template.',
            availableVariables: 'Available variables:',
            responseTemplate: 'Response Template',
            preview: 'Preview',
            errorResponseOverride: 'Error Response Override',
            errorResponseHint: 'Custom error templates for this route. Leave empty to use global templates.',
            autoGenFrom: 'Auto-generated from:',
            resetToAuto: 'Reset to Auto',
            standardVars: 'Standard Vars',
            dataColumns: 'Data Columns',
            selectDataSourceHint: 'Select a Data Source to see columns.',
            noColumnsFound: 'No columns found.',
            lineageTip: 'Tip:',
            lineageTipText: 'Click any variable to insert it into your JSON template. Use',
            lineageTipCode: '{{item.col}}',
            lineageTipSuffix: 'inside loops if mapping data manually.',
            additionalRestrictions: 'Additional Restrictions (Optional)',
            bypass: 'BYPASS',
            accessLevel: 'Access Level',
            accessLevelHint: 'Users with role level below this will receive 401/403 error',
            publicEndpoint: 'Public Endpoint',
            publicEndpointHint: 'Anyone can access without authentication',
            loginRequired: 'Login Required',
            loginRequiredHint: 'User must be logged in to access',
            adminOnly: 'Admin Only',
            adminOnlyHint: 'Only administrators can access',
            bindToDataSource: '1. Bind to Data Source',
            selectResourceLogic: '2. Select Resource Logic (Optional)',
            noBinding: 'No Binding (Static / Custom Logic)',
            rawTableData: 'Raw Table Data (Default)',
            noSpecificResources: 'No specific resources defined for this source. Using raw table access.',
        },
        options: {
            public: 'Public Endpoint',
            login: 'Login Required',
            moderator: 'Moderators',
            admin: 'Admin Only',
        },
    },
    errorTemplates: {
        title: 'Global Error Templates',
        subtitle: 'Customize API error responses',
        labels: {
            noCustomTemplate: 'No custom template',
            addCustomStatusCode: 'Add Custom Status Code',
            loading: 'Loading templates...',
        },
        statusCodes: {
            badRequest: 'Bad Request',
            unauthorized: 'Unauthorized',
            forbidden: 'Forbidden',
            notFound: 'Not Found',
            serverError: 'Server Error',
            customError: 'Custom Error',
        },
        buttons: {
            addTemplate: '+ Add Template',
            save: 'Save',
            cancel: 'Cancel',
            create: 'Create',
            add: 'Add',
        },
        placeholders: {
            templateJson: '{"status":"error","code":401,"errorCode":"AUTH_UNAUTHORIZED","message":"Unauthorized"}',
            statusCode: 'Status code (e.g. 422)',
            customTemplate: '{"status":"error","code":422,"errorCode":"CUSTOM_ERROR","message":"Custom error"}',
        },
        messages: {
            saved: 'Template saved',
            deleted: 'Template deleted',
            loadFailed: 'Failed to load templates',
            saveFailed: 'Failed to save',
            connectionError: 'Connection error',
            confirmDelete: 'Delete this template?',
        },
    },
    apiTester: {
        title: 'API Tester',
        subtitle: 'Test endpoints directly from the dashboard',
        labels: {
            recentRequests: 'Recent Requests',
            authentication: 'Authentication',
            autoInjected: '(auto-injected to headers)',
            headers: 'Headers',
            body: 'Body',
            jsonBody: 'JSON Body',
            response: 'Response',
            readyToTest: 'Ready to Test',
            readyToTestDesc: 'Enter a URL and click Send to test your API',
            required: 'REQUIRED',
            optional: 'OPTIONAL',
            ok: 'OK',
            error: 'Error',
            serverError: 'Server Error',
            loading: 'Loading...',
            ms: 'ms',
            xApiKey: 'x-api-key',
            authorization: 'Authorization',
        },
        placeholders: {
            enterUrl: 'Enter URL...',
            apiKey: 'pk_your_api_key_here',
            jwtToken: 'eyJhbGciOiJIUzI1NiIs...',
            headerName: 'Header name',
            headerValue: 'Value',
            jsonBody: '{"key": "value"}',
        },
        buttons: {
            send: 'Send',
            history: 'History',
            clear: 'Clear',
            copy: 'Copy',
            format: 'Format',
            addHeader: '+ Add Header',
        },
        messages: {
            urlRequired: 'URL is required',
            copied: 'Copied to clipboard',
            invalidJson: 'Invalid JSON',
            requestFailed: 'Request failed',
            apiKeyHint: 'Get API Key from API & CORS page. Get JWT Token from /auth/login response.',
        },
    },
    authRoutes: {
        title: 'Auth Routes',
        subtitle: 'Authentication dan user management endpoints',
        labels: {
            total: 'Total',
            auth: 'Auth',
            endpoints: 'endpoints',
            userAuthentication: 'User Authentication',
            requestBody: 'REQUEST BODY',
            successResponse: 'SUCCESS 200',
            errorResponse: 'ERROR 401/409',
            viewDetails: 'View Details',
            notes: 'Catatan',
            status: 'Status: ',
            notesLabel: 'Notes:',
            loading: 'Loading API Documentation...',
            loadFailed: 'Failed to Load Docs',
            tryAgain: 'Try Again',
        },
        buttons: {
            back: 'Back',
            test: 'Test',
            apiTester: 'API Tester',
            api: 'API ',
        },
        messages: {
            urlCopied: 'URL copied!',
        },
        notes: {
            userManagement: 'User Management → role super_admin',
            authHeader: 'Header: Authorization: Bearer <token>',
            clickTest: 'Klik Test untuk uji di API Tester',
        },
    },
} as const;
