export const MIDDLEWARE = {
    ERROR: {
        unauthorized: "MW.ERROR.UNAUTHORIZED",
        forbidden: "MW.ERROR.FORBIDDEN",
        invalid_token: "MW.ERROR.INVALID_TOKEN",
        rate_limit_exceeded: "MW.ERROR.RATE_LIMIT_EXCEEDED",
        csrf_invalid: "MW.ERROR.CSRF_INVALID",
        cors_blocked: "MW.ERROR.CORS_BLOCKED",
        MISSING_AUTH_HEADER: "MW.ERROR.MISSING_AUTH_HEADER",
        USER_NOT_AUTHENTICATED: "MW.ERROR.USER_NOT_AUTHENTICATED",
        INSUFFICIENT_ROLE: "MW.ERROR.INSUFFICIENT_ROLE",
        MISSING_PERMISSIONS: "MW.ERROR.MISSING_PERMISSIONS",
        SUPER_ADMIN_REQUIRED: "MW.ERROR.SUPER_ADMIN_REQUIRED",
        TOKEN_EXPIRED: "MW.ERROR.TOKEN_EXPIRED",
        TOKEN_INVALID: "MW.ERROR.TOKEN_INVALID",
        TOO_MANY_REQUESTS: "MW.ERROR.TOO_MANY_REQUESTS",
        TOO_MANY_REQUESTS_RETRY: "MW.ERROR.TOO_MANY_REQUESTS_RETRY",
        TOO_MANY_WRITE_OPS: "MW.ERROR.TOO_MANY_WRITE_OPS",
        REGISTRATION_LIMIT_EXCEEDED: "MW.ERROR.REGISTRATION_LIMIT_EXCEEDED",
        TOO_MANY_LOGIN_ATTEMPTS: "MW.ERROR.TOO_MANY_LOGIN_ATTEMPTS",
        MISSING_API_KEY: "MW.ERROR.MISSING_API_KEY",
        INVALID_API_KEY: "MW.ERROR.INVALID_API_KEY",
        SECURITY_ERROR: "MW.ERROR.SECURITY_ERROR",
        CSRF_MISSING: "MW.ERROR.CSRF_MISSING",
        CSRF_MISMATCH: "MW.ERROR.CSRF_MISMATCH"
    },
    SUCCESS: {
        // Add success messages here
    },
    LOG: {
        ADMIN_AUDIT: "[ADMIN AUDIT] %s | %s %s | IP: %s | Status: %s",
        SECURITY_CORS_REJECTED: "[SECURITY] CORS request rejected for origin: %s (not in whitelist)",
        SECURITY_WILDCARD_WARNING: "[SECURITY WARNING] Wildcard CORS (*) is enabled. This will be disabled in production.",
        CORS_DB_ERROR: "[CORS] Database error:",
        REQUEST_LOGGING_FAILED: "Request logging failed:"
    }
};
