export const API_KEYS_LABELS = {
    title: 'API & Security',
    subtitle: 'Manage API keys and configure CORS policies.',
    stats: {
        apiKeys: 'API Keys',
        activeKeys: 'Active Keys',
        corsDomains: 'CORS Domains',
        baseUrl: 'Base URL',
        registered: 'Registered',
        valid: 'Valid',
        allowed: 'Allowed',
        apiEndpoint: 'API Endpoint',
        activeNodes: 'Active Nodes',
    },
    sections: {
        apiAccessKeys: 'API Access Keys',
        corsDomainsTitle: 'CORS Domains',
        integrationGuide: 'Integration Guide',
        headersRequired: 'Headers yang Diperlukan',
        codeExamples: 'Contoh Kode Integrasi',
        authEndpoints: 'Auth Endpoints',
        crudPattern: 'CRUD Pattern',
        responseFormat: 'Response Format',
    },
    labels: {
        protected: 'Protected',
        keys: 'KEYS',
        domains: 'DOMAINS',
        quickStart: 'QUICK START',
        fullGuide: 'FULL GUIDE',
        requiredAllRequests: 'Wajib (Semua Request)',
        optionalAfterLogin: 'Optional (Setelah Login)',
        websiteJs: 'Website (JS/React)',
        mobileFlutter: 'Mobile (Flutter)',
        mobileReactNative: 'React Native',
        method: 'Method',
        path: 'Path',
        auth: 'Auth',
        description: 'Deskripsi',
        success: 'Success',
        error: 'Error',
        public: 'Public',
        token: 'Token',
    },
    buttons: {
        create: '+ Create',
        add: '+ Add',
        copy: 'Copy',
    },
    placeholders: {
        keyName: 'Key Name (e.g., Production)',
        domain: 'https://your-domain.com',
    },
    messages: {
        apiKeyCreated: 'API Key created',
        domainAdded: 'Domain added',
        deletedSuccess: 'Deleted successfully',
        copiedToClipboard: 'Copied to clipboard',
        urlCopied: 'URL copied',
        codeCopied: 'Code copied!',
        loadFailed: 'Failed to load API data',
        createKeyError: 'Error creating key',
        addDomainError: 'Error adding domain',
        deleteFailed: 'Delete failed',
        syncSuccess: 'Endpoints synced successfully',
        syncFailed: 'Sync failed, please try again',
    },
    confirm: {
        deleteApiKey: 'Delete API Key',
        removeCors: 'Remove CORS Domain',
        deleteMessage: 'Are you sure you want to delete',
        cannotUndo: 'This action cannot be undone.',
    },
} as const;
