/**
 * packages/config/src/labels/modules.ts
 * 
 * MODULE-SPECIFIC LABELS - Single Source of Truth
 * Each module's UI text defined here
 */

export const MODULE_LABELS = {
    // Data Sources Module
    dataSources: {
        title: 'Data Sources',
        subtitle: 'Manage your database tables and schemas',

        titles: {
            createResource: 'Create Resource',
            editResource: 'Edit Resource',
            createSource: 'Create Data Source',
        },

        buttons: {
            createSource: 'Create Data Source',
            newDataSource: 'New Data Source',
            editSchema: 'Edit Schema',
            viewData: 'View Data',
            createResource: 'Create Resource',
            addColumn: 'Add Column',
            removeColumn: 'Remove Column',
            importData: 'Import Data',
            importPlaceholder: '[{"name": "John", "email": "john@example.com"}, ...]',
            exportData: 'Export Data',
            viewResources: 'View Resources',
            hideResources: 'Hide Resources',
            cloneSource: 'Clone Source',
            deleteSource: 'Delete Source',
            backToSources: 'Back to Data Sources',
            goBack: 'Go Back',
            addRelation: 'Add Relation',
        },

        columns: {
            tableName: 'Table Name',
            rowCount: 'Rows',
            resourceCount: 'Resources',
            columnName: 'Column Name',
            columnType: 'Type',
            nullable: 'Nullable',
            defaultValue: 'Default',
            primaryKey: 'Primary Key',
            unique: 'Unique',
            indexed: 'Indexed',
        },

        forms: {
            tableName: 'Table Name',
            tableNamePlaceholder: 'Enter table name (e.g., products)',
            tableNameHint: 'Use lowercase with underscores',
            schemaTitle: 'Define Columns',
            schemaSubtitle: 'Add columns to your table',
            // Column Builder
            definedColumns: 'Defined Columns',
            configureSchemaStructure: 'Configure schema structure',
            addColumn: 'Add Column',
            addFirstColumn: 'Add First Column',
            startBuildingSchema: 'Start building your schema',
            addColumnsToDefine: 'Add columns to define your data structure',
            columnName: 'column_name',
            sqlLabel: 'SQL',
            required: 'Required',
            unique: 'Unique',
            untitledColumn: 'Untitled Column',
            unknownType: 'Unknown Type',
            allowedValues: 'Allowed Values (Comma Separated)',
            targetTable: 'Target Table',
            selectTable: 'Select a table...',
            maxLength: 'Max Length',
            // Hints
            slugHint: 'Will be auto-generated from "title" or "name" column if available.',
            stringHint: 'Standard text field up to 65k chars, but recommend keeping it short.',
            relationHint: 'Creates a foreign key to another table.',
            // Create Source Form
            startFromTemplate: 'Start from a Template',
            choosePrebuilt: 'Choose a pre-built schema to get started instantly.',
            useTemplate: 'Use Template',
            basicInformation: 'Basic Information',
            displayName: 'Display Name',
            displayNamePlaceholder: 'e.g. Product Catalog',
            displayNameHint: 'Human-readable name for the dashboard.',
            tableNameSql: 'Table Name (SQL)',
            tableNameSqlPlaceholder: 'e.g. product_catalog',
            finalDatabaseTableName: 'Final database table name',
            description: 'Description',
            descriptionPlaceholder: 'Optional: What is this data source used for?',
            schemaDefinition: 'Schema Definition',
            schemaDefinitionSubtitle: 'Define the columns and data types for your table.',
            schemaValidationErrors: 'Schema Validation Errors',
            configuration: 'Configuration',
            timestamps: 'Timestamps',
            timestampsDescription: 'Automatically maintain created_at and updated_at columns.',
            softDelete: 'Soft Delete',
            softDeleteDescription: 'Don\'t permanently delete rows. Instead, set a deleted_at timestamp.',
            pleaseFixValidation: 'Please fix validation errors',
        },


        labels: {
            sources: 'Sources',
            tables: 'Tables',
            records: 'Records',
            activeConnections: 'Active Connections',
            schemasDefined: 'Schemas Defined',
            totalRows: 'Total Rows',
            tableData: 'Table Data',
            viewAndManageRecords: 'View and manage records',
            schema: 'Schema',
            editColumnsTypes: 'Edit columns & types',
            apiResources: 'API Resources',
            noEndpointsConfigured: 'No API endpoints configured.',
            createResourceToExpose: 'Create a resource to expose this data via API.',
            hasJoins: 'Has Joins',
            filters: 'Filters',
            public: 'Public',
            protected: 'Protected',
            active: 'Active',
            draft: 'Draft',
            system: 'System',
            loadingDataSources: 'Loading data sources...',
            httpGet: 'GET',
            httpPost: 'POST',
            httpPut: 'PUT',
            httpDelete: 'DELETE',
            // Page labels
            loading: 'Loading...',
            data: 'Data',
            manageRowsFor: 'Manage rows for',
            loadingSourceDetails: 'Loading source details...',
            loadingDetails: 'Loading details...',
            forSource: 'for',
            // Resource Form
            endpointDetails: 'Endpoint Details',
            internalName: 'Internal Name',
            urlSlug: 'URL Slug',
            responseFields: 'Response Fields',
            selectFieldsHint: 'Select which columns to include in the JSON response.',
            noColumnsInSchema: 'No columns defined in schema.',
            allFieldsSelected: 'All fields selected.',
            selectSpecificFields: 'Select specific fields to restrict the output.',
            computedFields: 'Computed Fields',
            computedFieldsHint: 'Create new fields using SQL expressions (e.g. `price * 0.2` as `tax`).',
            noComputedFields: 'No computed fields defined.',
            addComputedField: 'Add Computed Field',
            addAnotherField: 'Add Another Field',
            aggregates: 'Aggregates',
            aggregatesHint: 'Calculate totals, averages, and counts instead of listing rows.',
            noAggregates: 'No aggregates defined. Returning standard row data.',
            addAggregate: 'Add Aggregate',
            addAnotherAggregate: 'Add Another Aggregate',
            relatedData: 'Related Data',
            relatedDataHint: 'Include data from related tables (eager loading).',
            defineRelationsFirst: 'Define relations in the Data Source structure first.',
            includeColumns: 'Include Columns',
            relationsJoins: 'Relations (JOINs)',
            relationsJoinsHint: 'Connect to other data sources to fetch related data.',
            noRelationsDefined: 'No relations defined.',
            addRelation: 'Add Relation',
            addAnotherRelation: 'Add Another Relation',
            sqlSelect: 'SELECT ... ,',
            sqlAs: 'AS',
            apiPrefix: '/api/v1/',
            trash: 'Trash',
            trashSubtitle: 'Recover deleted data sources or permanently destroy them.',
            loadingTrash: 'Loading Trash...',
            backToDataSources: 'Back to List',
            viewTrash: 'View Trash',
            trashEmpty: 'Trash is Empty',
            trashEmptyDesc: 'No deleted data sources found.',
            deletedAt: 'Deleted at',
            restore: 'Restore',
            deletePermanently: 'Delete Permanently',
            targetTable: 'Target Table',
            aliasOptional: 'Alias (Optional)',
            onCondition: 'ON CONDITION',
            selectSourceColumn: 'Select Source Column',
            selectTargetColumn: 'Select Target Column',
            defaultFilters: 'Default Filters',
            defaultFiltersHint: 'Apply server-side filters. These will be applied before any client-side query parameters.',
            noDefaultFilters: 'No default filters. All data is accessible.',
            addFilter: 'Add Filter',
            selectField: 'Select Field',
            configuration: 'Configuration',
            defaultSortConfig: 'Default Sort Config',
            limitPerPage: 'Limit Per Page',
            publicAccess: 'Public Access',
            publicAccessWarning: 'This endpoint will be accessible by anyone without an API key.',
            protectedAccessNote: 'Access requires a valid API Key (Recommended).',
        },

        messages: {
            success: {
                sourceCreated: 'Data source created successfully',
                sourceDeleted: 'Data source deleted',
                sourceCloned: 'Data source cloned successfully',
                sourceArchived: 'Data source archived',
                sourceRestored: 'Data source restored',
                schemaUpdated: 'Schema updated successfully',
                columnAdded: 'Column added successfully',
                columnDropped: 'Column dropped successfully',
                resourceCreated: 'Resource created successfully',
                resourceUpdated: 'Resource updated',
                resourceDeleted: 'Resource deleted',
                dataImported: 'Data imported successfully',
                rowInserted: 'Row inserted successfully',
                rowUpdated: 'Row updated successfully',
                rowDeleted: 'Row deleted successfully',
            },
            error: {
                schemaFailed: 'Failed to update schema',
                loadFailed: 'Failed to load data source',
                cloneFailed: 'Failed to clone data source',
                archiveFailed: 'Failed to archive data source',
                restoreFailed: 'Failed to restore data source',
                resourceLoadFailed: 'Failed to load resources',
                resourceCreateFailed: 'Failed to create resource',
                resourceUpdateFailed: 'Failed to update resource',
                resourceDeleteFailed: 'Failed to delete resource',
                dataLoadFailed: 'Failed to load data',
                rowInsertFailed: 'Failed to insert row',
                rowUpdateFailed: 'Failed to update row',
                rowDeleteFailed: 'Failed to delete row',
                network: 'Network error. Please try again.',
                notFound: 'Data source not found',
                sourceNotFound: 'Data source not found',
                resourceNotFound: 'Resource not found',
            },
            confirm: {
                deleteSource: 'Are you sure you want to delete this data source? This will also delete all associated data.',
                dropColumn: 'Dropping this column will permanently delete all data in it.',
                deleteRow: 'Are you sure you want to delete this record? This action cannot be undone.',
                deleteResource: 'Are you sure you want to delete this resource?',
                deleteRelation: 'Delete Relation?',
                restoreSource: 'Restore Data Source?',
                destroySource: 'Delete Permanently?',
                confirmRestore: 'Are you sure you want to restore this data source?',
                confirmDestroy: 'Are you sure you want to permanently delete this data source? This action cannot be undone and will DROP the database table.',
            },
            warnings: {
                systemTableRestricted: 'System Table Restricted',
                restrictedColSelection: 'Direct column selection is disabled for system tables to ensure security and data integrity.',
                standardFieldsAuto: 'Standard fields (e.g. ID, Names) will be handled automatically by the API.',
            },
            // Relations
            relations: {
                title: 'Relations',
                addRelation: 'Add Relation',
                noRelations: 'No relations defined',
                addToLink: 'Add a relation to link this data source to others',
                createRelationship: 'Create a relationship to another data source',
                loadingRelations: 'Loading relations...',
                targetTable: 'Target Table',
                targetTableDesc: 'Select the table to connect to',
                relationType: 'Relation Type',
                relationTypeDesc: 'Define how the tables relate',
                aliasOptional: 'Alias (optional)',
                aliasOptionalDesc: 'Custom name for API responses',
                aliasPlaceholder: 'e.g., user, tags, profile',
                aliasDescription: 'This name will be used in API responses',
                noTargets: 'No available targets found.',
                selectTarget: 'Select a target',
                fk: 'FK',
                pivot: 'Pivot',
                as: 'as',
                updateMetadata: 'Update metadata for',
                targetConfig: 'Target Configuration',
                fixedProps: 'Fixed physical properties',
                fkColumn: 'Foreign Key Column',
                defineRel: 'Define how the tables relate',
                customName: 'Custom name for API responses',
            },

            validation: {
                columnNameRequired: 'Column name is required',
                columnTypeRequired: 'Column type is required',
                resourceNameRequired: 'Resource name is required',
                tableNameRequired: 'Table name is required',
                minOneColumn: 'Add at least one column',
                invalidSchema: 'Invalid schema definition',
                slugRequired: 'Slug is required',
                fieldsRequired: 'At least one field must be selected',
            },
        },

        empty: {
            title: 'No Data Sources Yet',
            description: 'Create your first schema to start generating API endpoints instantly.',
        },
    },

    // Users Module
    users: {
        title: 'User Management',
        subtitle: 'Manage user accounts and access',

        labels: {
            userListTab: 'User List',
            filterPlaceholder: 'Search by name or email...',
            status: 'Status',
            role: 'Role',
            dateOrder: 'Date Order',
            allStatuses: 'All Statuses',
            active: 'Active',
            inactive: 'Inactive',
            allRoles: 'All Roles',
            newest: 'Newest first',
            oldest: 'Oldest first',
            rowsPerPage: 'Rows per page',
            user: 'User',
            level: 'Level',
            actions: 'Actions',
            page: 'Page',
            of: 'of',
        },

        columns: {
            username: 'Username',
            email: 'Email',
            role: 'Role',
            lastLogin: 'Last Login',
        },

        buttons: {
            addUser: 'Add User',
            create: 'Create',
            cancel: 'Cancel',
            save: 'Save',
            edit: 'Edit',
            delete: 'Delete',
            clearFilters: 'Clear filters',
            resetPassword: 'Reset Password',
            assignRole: 'Assign Role',
            suspendUser: 'Suspend User',
        },

        modal: {
            addTitle: 'Add User',
            editTitle: 'Edit User',
            usernameLabel: 'Username',
            emailLabel: 'Email',
            passwordLabel: 'Password',
            roleLabel: 'Role',
            usernamePlaceholder: 'john_doe',
            emailPlaceholder: 'john@example.com',
            passwordPlaceholder: 'Password',
        },

        messages: {
            created: 'User created!',
            updated: 'User updated!',
            deleted: 'User deleted',
            statusToggled: 'Status updated',
            fetchFailed: 'Failed to fetch users',
            createFailed: 'Failed to create user',
            connectionError: 'Connection error',
            empty: 'No users found',
            confirmDelete: 'Delete this user?',
            noResults: 'No users match the filters',
            passwordReset: 'Password reset email sent',
        },
    },

    // API Explorer Module (Standalone)
    apiExplorer: {
        title: 'API Explorer',
        subtitle: 'Discover and test your APIs',
    },

    // API Management Module
    apiManagement: {
        title: 'API Management',
        subtitle: 'Manage dynamic API routes and data binding',

        labels: {
            loading: 'Loading API Management...',
            categories: 'Categories',
            endpoints: 'Endpoints',
            endpoint: 'endpoint',
            noCategories: 'No categories yet',
            noEndpoints: 'No endpoints in this category',
            allCategories: 'All Cat.',
            method: 'Method',
            name: 'Name',
            description: 'Description',
            path: 'Path',
            roles: 'Roles',
            permissions: 'Permissions',
            minLevel: 'Min Level',
            levelShort: 'Lv.',
            dataSource: 'Data Source',
            resource: 'Resource',
            responseType: 'Response Type',
            staticJson: 'Static JSON',
            active: 'Active',
            inactive: 'Inactive',
            publicRoutes: 'Public Routes',
            authRequired: 'Auth Required',
            responseData: 'Response Data',
            noneSelected: 'None selected',
            selectCategory: 'Select category',
            selectDataSource: 'Select Data Source',
            selectResource: 'Select Resource',
            noDataSources: 'No data sources',
            noResources: 'No resources',
            rateLimit: 'Rate Limit',
            apiKey: 'API Key',
            lastUsed: 'Last Used',
            tableData: 'Table Data (Default)',
        },

        buttons: {
            createEndpoint: 'Create Endpoint',
            generateKey: 'Generate API Key',
            testEndpoint: 'Test Endpoint',
            new: 'New',
            newEndpoint: 'New Endpoint',
            newCategory: 'New Category',
            edit: 'Edit',
            delete: 'Delete',
            cancel: 'Cancel',
            save: 'Save',
            saveCategory: 'Save Category',
            saveEndpoint: 'Save Endpoint',
            test: 'Test',
            copy: 'Copy',
            clone: 'Clone',
            auth: 'Auth',
            routes: 'Routes',
            apiTester: 'API Tester',
            back: 'Back',
        },

        columns: {
            endpoint: 'Endpoint',
            method: 'Method',
            rateLimit: 'Rate Limit',
            apiKey: 'API Key',
            lastUsed: 'Last Used',
        },

        placeholders: {
            categoryName: 'Category name',
            categoryDescription: 'Category description (optional)',
            endpointPath: '/path/to/endpoint',
            endpointDescription: 'Endpoint description',
            jsonData: 'JSON Response Data',
            rolesCommaSep: 'Roles (comma separated)',
            permissionsCommaSep: 'Permissions (comma separated)',
            searchEndpoints: 'Search endpoints...',
        },

        messages: {
            categorySaved: 'Category saved',
            categoryDeleted: 'Category deleted',
            endpointSaved: 'Endpoint saved',
            endpointDeleted: 'Endpoint deleted',
            endpointToggled: 'Endpoint status updated',
            copiedPath: 'Path copied!',
            confirmDeleteCategory: 'Delete this category?',
            confirmDeleteEndpoint: 'Delete this endpoint?',
            fetchError: 'Failed to fetch data',
            saveError: 'Failed to save',
            deleteError: 'Failed to delete',
            swaggerExported: 'Swagger JSON exported!',
            schemaCopied: 'Schema copied',
            noDescription: 'No description',
            noDescriptionProvided: 'No description provided for this endpoint.',
        },

        explorer: {
            developerPortal: 'Developer Portal',
            title: 'API Explorer',
            subtitle: 'Discover, test, and integrate APIs directly into your application. Download the OpenAPI specification for seamless integration.',
            downloadOpenApi: 'Download OpenAPI',
            requiredRoleLevel: 'Required Role Level:',
            category: 'Category:',
            uncategorized: 'Uncategorized',
            responseSchema: 'Response Schema',
            viewDetails: 'View Details',
            tryItOut: 'Try it out',
            noEndpointSelected: 'No Endpoint Selected',
            selectEndpointHint: 'Select an endpoint from the sidebar to view details',
        },

        tabs: {
            basic: 'Basic Info',
            data: 'Data Binding',
            mutation: 'Mutation',
            security: 'Security',
            response: 'Response',
            test: 'Quick Test',
        },

        detail: {
            fullUrl: 'Full URL',
            requestInfo: 'Request Info',
            method: 'Method',
            contentType: 'Content-Type',
            security: 'Security',
            codeExamples: 'Code Examples',
            responseTemplate: 'Response Template',
            dataSource: 'Data Source',
            status: 'Status',
            publicAccess: 'Public Access',
            minRoleLevel: 'Min Role Level',
            noDataSource: 'No data source',
            active: 'Active',
            inactive: 'Inactive',
            backToList: '← Back to List',
            edit: 'Edit',
            test: 'Test',
            endpointNotFound: 'Endpoint not found',
            // Error Response Info for Frontend Integration
            errorResponses: 'Error Responses',
            errorResponsesHint: 'Use errorCode for i18n translations in your frontend',
            successResponse: 'Success Response',
            possibleErrors: 'Possible Errors',
            errorCode: 'Error Code',
            httpStatus: 'HTTP Status',
            defaultMessage: 'Default Message',
            autoGenerated: 'Auto-generated',
            customOverride: 'Custom Override',
        },

        mutation: {
            title: 'Write Operation Configuration',
            operationBehavior: 'Operation Behavior',
            ownershipSecurity: 'Ownership & Security',
            restrictToOwner: 'Restrict to Owner',
            restrictToOwnerHint: 'Only allow users to modify their own records',
            ownershipColumn: 'Ownership Column',
            ownershipColumnHint: 'Column in the table that stores the Owner ID',
            fieldControl: 'Field Control',
            writableFields: 'Writable Fields (JSON Array)',
            writableFieldsHint: 'Leave empty to allow all (except protected)',
            protectedFields: 'Protected Fields (JSON Array)',
            autoPopulate: 'Auto-Populate (JSON Object)',
            // Column Selector UI
            columnSelector: 'Column Configuration',
            columnSelectorHint: 'Click columns to toggle their write permission',
            selectDataSourceFirst: 'Select a Data Source first to see available columns',
            noColumnsAvailable: 'No columns available for this data source',
            legendWritable: 'Writable',
            legendProtected: 'Protected',
            legendAutoPopulate: 'Auto-Populate',
            validationRules: 'Validation Rules',
            validationHint: 'Enter validation rules for each writable column',
            validationSyntax: 'Syntax: required, minLength:N, maxLength:N, format:email|url, enum:val1,val2',
            // Auto-Populate Dropdown Options
            autoPopulateHint: 'Select fields to auto-fill with system values',
            autoPopNone: '— No auto-fill —',
            autoPopUserId: '👤 User ID ({{USER_ID}})',
            autoPopUserIdRecommended: '⭐ Recommended: User ID ({{USER_ID}})',
            autoPopNow: '🕐 Current Time ({{NOW}})',
            autoPopUserRole: '🛡️ User Role ({{USER_ROLE}})',
            relationArrow: '→ ',
        },

        misc: {
            dangerZone: 'Danger Zone',
            openInTester: 'Open in API Tester',
            clickToTest: 'Click the button below to test this endpoint in the API Tester',
            noEndpointsOne: 'No endpoints defined yet',
            noEndpointsTwo: 'Click "New Endpoint" to create your first API route',
            noEndpointsFilter: 'No endpoints match your filters',
            tryAdjusting: 'Try adjusting your search or filter criteria',
            noneSelected: 'None selected',
            selectToAdd: 'Select to add...',
            dataPreview: 'Data Preview',
            dataPreviewHint: 'Data from this source will be injected into {{DATA}} variable in your response template.',
            availableVariables: 'Available variables:',
            responseTemplate: 'Response Template',
            preview: 'Preview',
            errorResponseOverride: 'Error Response Override',
            errorResponseHint: 'Custom error templates for this route. Leave empty to use global templates.',
            autoGenFrom: 'Auto-generated from:',
            resetToAuto: 'Reset to Auto',
            // DataLineageHelper
            standardVars: 'Standard Vars',
            dataColumns: 'Data Columns',
            selectDataSourceHint: 'Select a Data Source to see columns.',
            noColumnsFound: 'No columns found.',
            lineageTip: 'Tip:',
            lineageTipText: 'Click any variable to insert it into your JSON template. Use',
            lineageTipCode: '{{item.col}}',
            lineageTipSuffix: 'inside loops if mapping data manually.',
            additionalRestrictions: 'Additional Restrictions (Optional)',
            bypass: 'BYPASS',
            accessLevel: 'Access Level',
            accessLevelHint: 'Users with role level below this will receive 401/403 error',
            publicEndpoint: 'Public Endpoint',
            publicEndpointHint: 'Anyone can access without authentication',
            loginRequired: 'Login Required',
            loginRequiredHint: 'User must be logged in to access',
            adminOnly: 'Admin Only',
            adminOnlyHint: 'Only administrators can access',
            bindToDataSource: '1. Bind to Data Source',
            selectResourceLogic: '2. Select Resource Logic (Optional)',
            noBinding: 'No Binding (Static / Custom Logic)',
            rawTableData: 'Raw Table Data (Default)',
            noSpecificResources: 'No specific resources defined for this source. Using raw table access.',
        },

        options: {
            public: '🌍 Public Endpoint',
            login: '👤 Login Required',
            moderator: '🛡️ Moderators',
            admin: '👑 Admin Only',
        }
    },

    // API & Security Module (ApiView)
    api: {
        title: 'API & Security',
        subtitle: 'Manage API keys and configure CORS policies.',

        stats: {
            apiKeys: 'API Keys',
            activeKeys: 'Active Keys',
            corsDomains: 'CORS Domains',
            baseUrl: 'Base URL',
            registered: 'Registered',
            valid: 'Valid',
            allowed: 'Allowed',
            apiEndpoint: 'API Endpoint',
        },

        sections: {
            apiAccessKeys: 'API Access Keys',
            corsDomainsTitle: 'CORS Domains',
            integrationGuide: 'Integration Guide',
            headersRequired: 'Headers yang Diperlukan',
            codeExamples: 'Contoh Kode Integrasi',
            authEndpoints: 'Auth Endpoints',
            crudPattern: 'CRUD Pattern',
            responseFormat: 'Response Format',
        },

        labels: {
            protected: 'Protected',
            keys: 'KEYS',
            domains: 'DOMAINS',
            quickStart: 'QUICK START',
            fullGuide: 'FULL GUIDE',
            requiredAllRequests: 'Wajib (Semua Request)',
            optionalAfterLogin: 'Optional (Setelah Login)',
            websiteJs: 'Website (JS/React)',
            mobileFlutter: 'Mobile (Flutter)',
            mobileReactNative: 'React Native',
            method: 'Method',
            path: 'Path',
            auth: 'Auth',
            description: 'Deskripsi',
            success: 'Success',
            error: 'Error',
            public: 'Public',
            token: 'Token',
        },

        buttons: {
            create: '+ Create',
            add: '+ Add',
            copy: 'Copy',
        },

        placeholders: {
            keyName: 'Key Name (e.g., Production)',
            domain: 'https://your-domain.com',
        },

        messages: {
            apiKeyCreated: 'API Key created',
            domainAdded: 'Domain added',
            deletedSuccess: 'Deleted successfully',
            copiedToClipboard: 'Copied to clipboard',
            urlCopied: 'URL copied',
            codeCopied: 'Code copied!',
            loadFailed: 'Failed to load API data',
            createKeyError: 'Error creating key',
            addDomainError: 'Error adding domain',
            deleteFailed: 'Delete failed',
        },

        confirm: {
            deleteApiKey: 'Delete API Key',
            removeCors: 'Remove CORS Domain',
            deleteMessage: 'Are you sure you want to delete',
            cannotUndo: 'This action cannot be undone.',
        },
    },

    // Storage Module
    storage: {
        title: 'Storage Analytics',
        subtitle: 'Database storage monitoring and table management',

        buttons: {
            refresh: 'Refresh',
            cleanup: 'Cleanup',
            delete: 'Delete',
            cancel: 'Cancel',
        },

        labels: {
            databaseStorage: 'Database Storage',
            tables: 'Tables',
            active: 'Active',
            largestTable: 'Largest Table',
            mostRows: 'Most Rows',
            indexRatio: 'Index Ratio',
            indexData: 'Index vs Data',
            data: 'Data',
            index: 'Index',
            overhead: 'Overhead',
            totalRows: 'Total Rows',
            rows: 'rows',
            connectedTo: 'Connected to',
            databaseTables: 'Database Tables',
            tablesCount: 'tables',
            noTablesFound: 'No tables found',
            noDatabaseConnected: 'No database connected',
            system: 'System',
            systemTables: 'System Tables',
            userTables: 'Custom Tables',
            mb: 'MB',
            na: 'N/A',
            percent: '%',
        },

        messages: {
            loadFailed: 'Failed to load storage stats',
            connectionFailed: 'Database connection failed',
            tableDeleted: 'Table deleted successfully',
            deleteFailed: 'Failed to delete table',
            cleanupCompleted: 'Cleanup completed',
            cleanupFailed: 'Cleanup failed',
            confirmDelete: 'Delete Table',
            deleteWarning: 'This action cannot be undone.',
        },
    },

    // Settings Module - MOVED TO @cp/settings-manager
    // settings: { ... },

    // Monitor Module
    monitor: {
        title: 'API Monitor',
        subtitle: 'Real-time API request monitoring and analytics.',

        labels: {
            liveStatus: 'Live - Refreshes every 30s',
            totalRequests: 'Total Requests',
            allTime: 'All Time',
            successful: 'Successful',
            successCodes: '2xx/3xx',
            failed: 'Failed',
            failedCodes: '4xx/5xx',
            avgLatency: 'Avg Latency',
            response: 'Response',
            ms: 'ms',
            healthScore: 'Health Score',
            uptime: 'Uptime',
            success: 'Success',
            recentActivity: 'Request Logs',
            logs: 'logs',
            status: 'Status',
            endpoint: 'Endpoint',
            latency: 'Latency',
            time: 'Time',
            percent: '%',
            // New labels for enhanced features
            ip: 'IP Address',
            userAgent: 'User Agent',
            origin: 'Origin',
            method: 'Method',
            allMethods: 'All Methods',
            allStatus: 'All Status',
            success2xx: 'Success (2xx)',
            clientError4xx: 'Client Error (4xx)',
            serverError5xx: 'Server Error (5xx)',
            searchPlaceholder: 'Search by endpoint...',
            noLogs: 'No API logs recorded yet',
            viewDetails: 'View Details',
            requestDetails: 'Request Details',
            clientInfo: 'Client Information',
            performanceInfo: 'Performance',
            showing: 'Showing',
            of: 'of',
            requests: 'requests',
            filters: 'Filters',
            clearFilters: 'Clear',
            exportCsv: 'Export CSV',
            refresh: 'Refresh',
        },

        messages: {
            loadFailed: 'Monitor data failed',
            connectionFailed: 'Connection failed',
            exported: 'Logs exported to CSV',
            refreshed: 'Data refreshed',
        },
    },

    // Permissions Module
    permissions: {
        title: 'Permission Manager',
        subtitle: 'Define granular permissions for users.',

        labels: {
            other: 'other',
            namePlaceholder: 'read:products',
            groupPlaceholder: 'products',
            descriptionPlaceholder: 'Allows reading products',
        },

        buttons: {
            addPermission: 'Add Permission',
            create: 'Create',
            cancel: 'Cancel',
        },

        modal: {
            addTitle: 'Add Permission',
            nameLabel: 'Name',
            groupLabel: 'Group',
            descriptionLabel: 'Description',
        },

        messages: {
            created: 'Permission created!',
            deleted: 'Deleted',
            fetchFailed: 'Failed to fetch permissions',
            createFailed: 'Failed',
            connectionError: 'Connection error',
            empty: 'No permissions defined. Create your first one above.',
            confirmDelete: 'Delete this permission?',
        },
    },

    // Roles Module
    roles: {
        title: 'Role Manager',
        subtitle: 'Manage user roles and access levels.',

        labels: {
            level: 'Level',
            superAdmin: 'Super Admin',
            activeRole: 'Active',
            inactiveRole: 'Inactive',
            permissions: 'Permissions',
            other: 'other',
            namePlaceholder: 'editor',
            displayNamePlaceholder: 'Editor',
            descriptionPlaceholder: 'Can edit content',
            levelPlaceholder: '50',
        },

        buttons: {
            addRole: 'Add Role',
            create: 'Create',
            cancel: 'Cancel',
            save: 'Save',
            edit: 'Edit',
        },

        modal: {
            addTitle: 'Add Role',
            editTitle: 'Edit Role',
            nameLabel: 'Name',
            displayNameLabel: 'Display Name',
            descriptionLabel: 'Description',
            levelLabel: 'Level',
            superAdminLabel: 'Super Admin (bypasses all permissions)',
        },

        messages: {
            created: 'Role created!',
            updated: 'Role updated!',
            deleted: 'Deleted',
            fetchFailed: 'Failed to fetch roles',
            createFailed: 'Failed',
            connectionError: 'Connection error',
            empty: 'No roles defined. Create your first one above.',
            confirmDelete: 'Delete this role?',
        },
    },

    // Error Templates Module
    errorTemplates: {
        title: 'Global Error Templates',
        subtitle: 'Customize API error responses',

        labels: {
            noCustomTemplate: 'No custom template',
            addCustomStatusCode: 'Add Custom Status Code',
            loading: 'Loading templates...',
        },

        statusCodes: {
            badRequest: 'Bad Request',
            unauthorized: 'Unauthorized',
            forbidden: 'Forbidden',
            notFound: 'Not Found',
            serverError: 'Server Error',
            customError: 'Custom Error',
        },

        buttons: {
            addTemplate: '+ Add Template',
            save: 'Save',
            cancel: 'Cancel',
            create: 'Create',
            add: 'Add',
        },

        placeholders: {
            templateJson: '{"status":"error","code":401,"errorCode":"AUTH_UNAUTHORIZED","message":"Unauthorized"}',
            statusCode: 'Status code (e.g. 422)',
            customTemplate: '{"status":"error","code":422,"errorCode":"CUSTOM_ERROR","message":"Custom error"}',
        },

        messages: {
            saved: 'Template saved',
            deleted: 'Template deleted',
            loadFailed: 'Failed to load templates',
            saveFailed: 'Failed to save',
            connectionError: 'Connection error',
            confirmDelete: 'Delete this template?',
        },
    },

    // API Tester Module
    apiTester: {
        title: 'API Tester',
        subtitle: 'Test endpoints directly from the dashboard',

        labels: {
            recentRequests: 'Recent Requests',
            authentication: 'Authentication',
            autoInjected: '(auto-injected to headers)',
            headers: 'Headers',
            body: 'Body',
            jsonBody: 'JSON Body',
            response: 'Response',
            readyToTest: 'Ready to Test',
            readyToTestDesc: 'Enter a URL and click Send to test your API',
            required: 'REQUIRED',
            optional: 'OPTIONAL',
            ok: 'OK',
            error: 'Error',
            serverError: 'Server Error',
            loading: 'Loading...',
            ms: 'ms',
            xApiKey: 'x-api-key',
            authorization: 'Authorization',
        },

        placeholders: {
            enterUrl: 'Enter URL...',
            apiKey: 'pk_your_api_key_here',
            jwtToken: 'eyJhbGciOiJIUzI1NiIs...',
            headerName: 'Header name',
            headerValue: 'Value',
            jsonBody: '{"key": "value"}',
        },

        buttons: {
            send: 'Send',
            history: 'History',
            clear: 'Clear',
            copy: 'Copy',
            format: 'Format',
            addHeader: '+ Add Header',
        },

        messages: {
            urlRequired: 'URL is required',
            copied: 'Copied to clipboard',
            invalidJson: 'Invalid JSON',
            requestFailed: 'Request failed',
            apiKeyHint: 'Get API Key from API & CORS page. Get JWT Token from /auth/login response.',
        },
    },

    // Auth Routes Module
    authRoutes: {
        title: 'Auth Routes',
        subtitle: 'Authentication dan user management endpoints',

        labels: {
            total: 'Total',
            auth: 'Auth',
            endpoints: 'endpoints',
            userAuthentication: 'User Authentication',
            requestBody: 'REQUEST BODY',
            successResponse: 'SUCCESS 200',
            errorResponse: 'ERROR 401/409',
            notes: 'Catatan',
            status: 'Status: ',
            notesLabel: 'Notes:',
            loading: 'Loading API Documentation...',
            loadFailed: 'Failed to Load Docs',
            tryAgain: 'Try Again',
        },

        buttons: {
            back: 'Back',
            test: 'Test',
            apiTester: 'API Tester',
            api: 'API ',
        },

        messages: {
            urlCopied: 'URL copied!',
        },

        notes: {
            userManagement: 'User Management → role super_admin',
            authHeader: 'Header: Authorization: Bearer <token>',
            clickTest: 'Klik Test untuk uji di API Tester',
        },
    },

    // Dashboard Module
    dashboard: {
        title: 'Dashboard',
        subtitle: 'Real-time overview of your engine performance and status.',
        liveStatus: 'Live System Status',
        sections: {
            totalUsers: 'Total Users',
            activeRegistered: 'Actively Registered',
            apiRequests: 'API Requests',
            totalTraffic: 'Total Traffic',
            successRate: 'Success Rate',
            deliveryHealth: 'Delivery Health',
            storageUsage: 'Storage Usage',
            assetsVolume: 'Assets Volume',
            systemActivity: 'System Activity',
            latestInteractions: 'Latest API interactions',
            infrastructure: 'Infrastructure',
            mainGateway: 'Main Gateway',
            publicApiEntry: 'Your public API entry'
        },
        labels: {
            activeEndpoints: 'Active Endpoints',
            securityKeys: 'Security Keys',
            systemHealth: 'System Health',
            liveStream: 'Live Stream',
            latency: 'latency',
            noActivity: 'No activity recorded',
            copyUrl: 'Copy Endpoint URL',
            copied: 'Gateway URL copied!',
            fetchError: 'Dashboard fetch error'
        }
    },
} as const;

export type ModuleLabels = typeof MODULE_LABELS;
