export const APP_USER_LABELS = {
    view: {
        title: 'App Users',
        subtitle: 'Manage target system end-users',
        addUser: 'Add App User',
    },
    confirm: {
        deleteTitle: 'Delete App User',
        deleteMessage: 'Are you sure you want to delete this app user? This action cannot be undone.',
        deleteConfirm: 'Delete',
    },
    table: {
        user: 'User',
        email: 'Email',
        role: 'Role',
        status: 'Status',
        joinedAt: 'Joined At',
        active: 'ACTIVE',
        inactive: 'INACTIVE',
        defaultRole: 'App User',
    },
    empty: {
        title: 'No app users found in this target system',
        subtitle: 'No app users match the filters',
    },
    filter: {
        searchPlaceholder: 'Search App Users...',
        totalUsers: 'Total Users',
        allStatuses: 'All Statuses',
        active: 'Active',
        inactive: 'Inactive',
        allRoles: 'All Roles',
        newest: 'Newest First',
        oldest: 'Oldest First',
        clear: 'Clear',
    },
    pagination: {
        showing: (start: number, end: number, total: number) => `Showing ${start}-${end} of ${total}`,
    },
    modal: {
        addTitle: 'Add App User',
        editTitle: 'Edit App User',
        usernameLabel: 'Username',
        usernamePlaceholder: 'Username',
        emailLabel: 'Email',
        emailPlaceholder: 'Email Address',
        passwordLabel: 'Password',
        passwordPlaceholder: 'Initial Password',
        roleLabel: 'Role',
        rolePlaceholder: 'Assign a role',
        level: (level: number) => `LEVEL ${level}`,
        privileged: 'PRIVILEGED',
        cancel: 'Cancel',
        create: 'Create User',
        save: 'Save Changes',
    },
} as const;
