import {
    Edit3, Gem, Check, Sparkles, Link, Lock, Zap, X, BarChart3,
    Trash2, Search, Settings, AlertTriangle, Table2, Key, Info,
    Database, Plus, BookOpen, HardDrive, FolderOpen, ArrowRight,
    Loader2, ArrowLeft, Copy, Unlink, Code, Download, Upload,
    RefreshCw, ChevronUp, ChevronDown, ClipboardList, FileText,
    Globe, Image, File,
} from 'lucide-react';

export const Icons = {
    edit: Edit3,
    gem: Gem,
    check: Check,
    sparkles: Sparkles,
    link: Link,
    lock: Lock,
    lightning: Zap,
    close: X,
    chart: BarChart3,
    delete: Trash2,
    search: Search,
    settings: Settings,
    warning: AlertTriangle,
    table: Table2,
    key: Key,
    info: Info,
    database: Database,
    plus: Plus,
    bookOpen: BookOpen,
    storage: HardDrive,
    folderOpen: FolderOpen,
    arrowRight: ArrowRight,
    loading: Loader2,
    arrowLeft: ArrowLeft,
    copy: Copy,
    linkOff: Unlink,
    code: Code,
    download: Download,
    upload: Upload,
    refresh: RefreshCw,
    chevronUp: ChevronUp,
    chevronDown: ChevronDown,
    clipboardList: ClipboardList,
    fileText: FileText,
    globe: Globe,
    image: Image,
    file: File,
    trash: Trash2,
} as const;

import {
    Key as IdIcon, Fingerprint, Hash, DollarSign, ToggleLeft,
    Calendar, Clock, Timer, Braces, List, CircleDot, Mail, Phone,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const DataTypeIcons: Record<string, LucideIcon> = {
    id: IdIcon,
    uuid: Fingerprint,
    // Numeric
    tinyint: Hash,
    smallint: Hash,
    mediumint: Hash,
    integer: Hash,
    bigint: Hash,
    decimal: DollarSign,
    float: BarChart3,
    double: BarChart3,
    bit: ToggleLeft,
    // String
    char: FileText,
    string: FileText,
    tinytext: FileText,
    text: FileText,
    mediumtext: FileText,
    longtext: FileText,
    // Binary/Blob
    binary: HardDrive,
    varbinary: HardDrive,
    tinyblob: HardDrive,
    blob: HardDrive,
    mediumblob: HardDrive,
    longblob: HardDrive,
    // Specialized
    slug: Link,
    email: Mail,
    phone: Phone,
    url: Globe,
    // Date/Time
    date: Calendar,
    time: Clock,
    datetime: Clock,
    timestamp: Timer,
    year: Calendar,
    // Misc
    boolean: ToggleLeft,
    json: Braces,
    enum: List,
    set: List,
    status: CircleDot,
    relation: Link,
    image: Image,
    file: File,
};

export type { LucideIcon };
