export const DATABASE_SCHEMA_LABELS = {
    title: 'Database Schema',
    subtitle: 'Manage your database tables and structure',

    titles: {
        createResource: 'Create Resource',
        editResource: 'Edit Resource',
        createSchema: 'Create Schema',
    },

    buttons: {
        createSchema: 'Create Schema',
        newSchema: 'New Schema',
        editSchema: 'Edit Schema',
        viewData: 'View Data',
        createResource: 'Create Resource',
        addColumn: 'Add Column',
        removeColumn: 'Remove Column',
        importData: 'Import Data',
        importPlaceholder: '[{"name": "John", "email": "john@example.com"}, ...]',
        exportData: 'Export Data',
        viewResources: 'View Resources',
        hideResources: 'Hide Resources',
        cloneSchema: 'Clone Schema',
        deleteSchema: 'Delete Schema',
        backToSchema: 'Back to Database Schema',
        goBack: 'Go Back',
        addRelation: 'Add Relation',
    },

    columns: {
        tableName: 'Table Name',
        rowCount: 'Rows',
        resourceCount: 'Resources',
        columnName: 'Column Name',
        columnType: 'Type',
        nullable: 'Nullable',
        defaultValue: 'Default',
        primaryKey: 'Primary Key',
        unique: 'Unique',
        indexed: 'Indexed',
    },

    forms: {
        tableName: 'Table Name',
        tableNamePlaceholder: 'Enter table name (e.g., products)',
        tableNameHint: 'Use lowercase with underscores',
        schemaTitle: 'Define Columns',
        schemaSubtitle: 'Add columns to your table',
        // Column Builder
        definedColumns: 'Defined Columns',
        configureSchemaStructure: 'Configure schema structure',
        addColumn: 'Add Column',
        addFirstColumn: 'Add First Column',
        startBuildingSchema: 'Start building your schema',
        addColumnsToDefine: 'Add columns to define your data structure',
        columnName: 'column_name',
        sqlLabel: 'SQL',
        required: 'Required',
        unique: 'Unique',
        untitledColumn: 'Untitled Column',
        unknownType: 'Unknown Type',
        allowedValues: 'Allowed Values (Comma Separated)',
        targetTable: 'Target Table',
        selectTable: 'Select a table...',
        maxLength: 'Max Length',
        // Hints
        slugHint: 'Will be auto-generated from "title" or "name" column if available.',
        stringHint: 'Standard text field up to 65k chars, but recommend keeping it short.',
        relationHint: 'Creates a foreign key to another table.',
        // Create Source Form
        startFromTemplate: 'Start from a Template',
        choosePrebuilt: 'Choose a pre-built schema to get started instantly.',
        useTemplate: 'Use Template',
        basicInformation: 'Basic Information',
        displayName: 'Display Name',
        displayNamePlaceholder: 'e.g. Product Catalog',
        displayNameHint: 'Human-readable name for the dashboard.',
        tableNameSql: 'Table Name (SQL)',
        tableNameSqlPlaceholder: 'e.g. product_catalog',
        finalDatabaseTableName: 'Final database table name',
        description: 'Description',
        descriptionPlaceholder: 'Optional: What is this data source used for?',
        schemaDefinition: 'Schema Definition',
        schemaDefinitionSubtitle: 'Define the columns and data types for your table.',
        schemaValidationErrors: 'Schema Validation Errors',
        configuration: 'Configuration',
        timestamps: 'Timestamps',
        timestampsDescription: 'Automatically maintain created_at and updated_at columns.',
        softDelete: 'Soft Delete',
        softDeleteDescription: 'Don\'t permanently delete rows. Instead, set a deleted_at timestamp.',
        pleaseFixValidation: 'Please fix validation errors',
    },


    labels: {
        sources: 'Sources',
        tables: 'Tables',
        records: 'Records',
        activeConnections: 'Active Connections',
        schemasDefined: 'Schemas Defined',
        totalRows: 'Total Rows',
        tableData: 'Table Data',
        viewAndManageRecords: 'View and manage records',
        schema: 'Schema',
        editColumnsTypes: 'Edit columns & types',
        apiResources: 'API Resources',
        noEndpointsConfigured: 'No API endpoints configured.',
        createResourceToExpose: 'Create a resource to expose this data via API.',
        hasJoins: 'Has Joins',
        filters: 'Filters',
        public: 'Public',
        protected: 'Protected',
        active: 'Active',
        draft: 'Draft',
        system: 'System',
        loadingDataSources: 'Loading data sources...',
        httpGet: 'GET',
        httpPost: 'POST',
        httpPut: 'PUT',
        httpDelete: 'DELETE',
        // Page labels
        loading: 'Loading...',
        data: 'Data',
        manageRowsFor: 'Manage rows for',
        loadingSourceDetails: 'Loading source details...',
        loadingDetails: 'Loading details...',
        forSource: 'for',
        // Resource Form
        endpointDetails: 'Endpoint Details',
        internalName: 'Internal Name',
        urlSlug: 'URL Slug',
        responseFields: 'Response Fields',
        selectFieldsHint: 'Select which columns to include in the JSON response.',
        noColumnsInSchema: 'No columns defined in schema.',
        allFieldsSelected: 'All fields selected.',
        selectSpecificFields: 'Select specific fields to restrict the output.',
        computedFields: 'Computed Fields',
        computedFieldsHint: 'Create new fields using SQL expressions (e.g. `price * 0.2` as `tax`).',
        noComputedFields: 'No computed fields defined.',
        addComputedField: 'Add Computed Field',
        addAnotherField: 'Add Another Field',
        aggregates: 'Aggregates',
        aggregatesHint: 'Calculate totals, averages, and counts instead of listing rows.',
        noAggregates: 'No aggregates defined. Returning standard row data.',
        addAggregate: 'Add Aggregate',
        addAnotherAggregate: 'Add Another Aggregate',
        relatedData: 'Related Data',
        relatedDataHint: 'Include data from related tables (eager loading).',
        defineRelationsFirst: 'Define relations in the Data Source structure first.',
        includeColumns: 'Include Columns',
        relationsJoins: 'Relations (JOINs)',
        relationsJoinsHint: 'Connect to other data sources to fetch related data.',
        noRelationsDefined: 'No relations defined.',
        addRelation: 'Add Relation',
        addAnotherRelation: 'Add Another Relation',
        sqlSelect: 'SELECT ... ,',
        sqlAs: 'AS',
        apiPrefix: '/api/v1/',
        trash: 'Trash',
        trashSubtitle: 'Recover deleted data sources or permanently destroy them.',
        loadingTrash: 'Loading Trash...',
        backToDataSources: 'Back to List',
        viewTrash: 'View Trash',
        trashEmpty: 'Trash is Empty',
        trashEmptyDesc: 'No deleted data sources found.',
        deletedAt: 'Deleted at',
        restore: 'Restore',
        deletePermanently: 'Delete Permanently',
        targetTable: 'Target Table',
        aliasOptional: 'Alias (Optional)',
        onCondition: 'ON CONDITION',
        selectSourceColumn: 'Select Source Column',
        selectTargetColumn: 'Select Target Column',
        defaultFilters: 'Default Filters',
        defaultFiltersHint: 'Apply server-side filters. These will be applied before any client-side query parameters.',
        noDefaultFilters: 'No default filters. All data is accessible.',
        addFilter: 'Add Filter',
        selectField: 'Select Field',
        configuration: 'Configuration',
        defaultSortConfig: 'Default Sort Config',
        limitPerPage: 'Limit Per Page',
        publicAccess: 'Public Access',
        publicAccessWarning: 'This endpoint will be accessible by anyone without an API key.',
        protectedAccessNote: 'Access requires a valid API Key (Recommended).',
    },

    messages: {
        success: {
            sourceCreated: 'Data source created successfully',
            sourceDeleted: 'Data source deleted',
            sourceCloned: 'Data source cloned successfully',
            sourceArchived: 'Data source archived',
            sourceRestored: 'Data source restored',
            schemaUpdated: 'Schema updated successfully',
            columnAdded: 'Column added successfully',
            columnDropped: 'Column dropped successfully',
            resourceCreated: 'Resource created successfully',
            resourceUpdated: 'Resource updated',
            resourceDeleted: 'Resource deleted',
            dataImported: 'Data imported successfully',
            rowInserted: 'Row inserted successfully',
            rowUpdated: 'Row updated successfully',
            rowDeleted: 'Row deleted successfully',
        },
        error: {
            schemaFailed: 'Failed to update schema',
            loadFailed: 'Failed to load data source',
            cloneFailed: 'Failed to clone data source',
            archiveFailed: 'Failed to archive data source',
            restoreFailed: 'Failed to restore data source',
            resourceLoadFailed: 'Failed to load resources',
            resourceCreateFailed: 'Failed to create resource',
            resourceUpdateFailed: 'Failed to update resource',
            resourceDeleteFailed: 'Failed to delete resource',
            dataLoadFailed: 'Failed to load data',
            rowInsertFailed: 'Failed to insert row',
            rowUpdateFailed: 'Failed to update row',
            rowDeleteFailed: 'Failed to delete row',
            network: 'Network error. Please try again.',
            notFound: 'Data source not found',
            sourceNotFound: 'Data source not found',
            resourceNotFound: 'Resource not found',
        },
        confirm: {
            deleteSource: 'Are you sure you want to delete this data source? This will also delete all associated data.',
            dropColumn: 'Dropping this column will permanently delete all data in it.',
            deleteRow: 'Are you sure you want to delete this record? This action cannot be undone.',
            deleteResource: 'Are you sure you want to delete this resource?',
            deleteRelation: 'Delete Relation?',
            restoreSource: 'Restore Data Source?',
            destroySource: 'Delete Permanently?',
            confirmRestore: 'Are you sure you want to restore this data source?',
            confirmDestroy: 'Are you sure you want to permanently delete this data source? This action cannot be undone and will DROP the database table.',
        },
        warnings: {
            systemTableRestricted: 'System Table Restricted',
            restrictedColSelection: 'Direct column selection is disabled for system tables to ensure security and data integrity.',
            standardFieldsAuto: 'Standard fields (e.g. ID, Names) will be handled automatically by the API.',
        },
        // Relations
        relations: {
            title: 'Relations',
            addRelation: 'Add Relation',
            noRelations: 'No relations defined',
            addToLink: 'Add a relation to link this data source to others',
            createRelationship: 'Create a relationship to another data source',
            loadingRelations: 'Loading relations...',
            targetTable: 'Target Table',
            targetTableDesc: 'Select the table to connect to',
            relationType: 'Relation Type',
            relationTypeDesc: 'Define how the tables relate',
            aliasOptional: 'Alias (optional)',
            aliasOptionalDesc: 'Custom name for API responses',
            aliasPlaceholder: 'e.g., user, tags, profile',
            aliasDescription: 'This name will be used in API responses',
            noTargets: 'No available targets found.',
            selectTarget: 'Select a target',
            fk: 'FK',
            pivot: 'Pivot',
            as: 'as',
            updateMetadata: 'Update metadata for',
            targetConfig: 'Target Configuration',
            fixedProps: 'Fixed physical properties',
            fkColumn: 'Foreign Key Column',
            defineRel: 'Define how the tables relate',
            customName: 'Custom name for API responses',
        },

        validation: {
            columnNameRequired: 'Column name is required',
            columnTypeRequired: 'Column type is required',
            resourceNameRequired: 'Resource name is required',
            tableNameRequired: 'Table name is required',
            minOneColumn: 'Add at least one column',
            invalidSchema: 'Invalid schema definition',
            slugRequired: 'Slug is required',
            fieldsRequired: 'At least one field must be selected',
        },
    },

    empty: {
        title: 'No Data Sources Yet',
        description: 'Create your first schema to start generating API endpoints instantly.',
    },
};
