import {
    Plus, Search, Zap, Lock, FileText, Rocket, Link, CheckCircle,
    Folder, GitBranch, X, Pencil, Trash2, Copy, FlaskConical, Power,
    ArrowLeft, Edit3, Send, ArrowRight, Code, File, Globe, Crown,
    Key, Link2, AlertTriangle, Upload, Shield, ChevronRight, Info,
    ChevronDown, Lightbulb, Users, Play, Clock, Sparkles, Download,
    Database, ChevronLeft, Terminal, Activity, Cloud, Settings,
} from 'lucide-react';

export const Icons = {
    plus: Plus,
    search: Search,
    zap: Zap,
    lock: Lock,
    fileText: FileText,
    rocket: Rocket,
    link: Link,
    checkCircle: CheckCircle,
    folder: Folder,
    branch: GitBranch,
    close: X,
    pencil: Pencil,
    trash: Trash2,
    copy: Copy,
    flask: FlaskConical,
    power: Power,
    arrowLeft: ArrowLeft,
    edit: Edit3,
    send: Send,
    arrowRight: ArrowRight,
    code: Code,
    file: File,
    globe: Globe,
    crown: Crown,
    key: Key,
    link2: Link2,
    warning: AlertTriangle,
    upload: Upload,
    shield: Shield,
    chevronRight: ChevronRight,
    info: Info,
    chevronDown: ChevronDown,
    tip: Lightbulb,
    users: Users,
    play: Play,
    clock: Clock,
    sparkles: Sparkles,
    download: Download,
    database: Database,
    chevronLeft: ChevronLeft,
    terminal: Terminal,
    activity: Activity,
    cloud: Cloud,
    settings: Settings,
    check: CheckCircle,
    error: AlertTriangle,
    back: ArrowLeft,
    delete: Trash2,
    loading: Clock,
} as const;
